name: Check Challenge-0 Completion

on:
  push:
    paths:
      - 'challenges/**'

jobs:
  check-challenge-0:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug Info
      run: |
        ls -R challenges

    - name: Check Challenge-0 completion
      run: |
        CHALLENGE_PATH="challenges/0-hello-world"

        # Iterate over language folders
        for LANG_FOLDER in "$CHALLENGE_PATH"/*; do
          if [ -d "$LANG_FOLDER" ]; then
            GITHUB_USERNAME="$GITHUB_ACTOR"
            USER_PATH="$LANG_FOLDER/$GITHUB_USERNAME"

            if [ -d "$USER_PATH" ]; then
              echo "Challenge-0 completed by $GITHUB_USERNAME in language: $(basename "$LANG_FOLDER")."
              # Add your logic here to perform further steps if needed
              exit 0  # Exiting with a successful exit code
            fi
          fi
        done

        # If no matching user folder is found, exit with a non-successful code
        echo "Challenge-0 not completed by $GITHUB_USERNAME in any language folder."
        exit 1
