name: Check Challenge-0 Completion

on:
  push:
    paths:
      - 'challenges/**'

jobs:
  check-challenge-0:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug Info
      run: |
        ls -R challenges

    - name: Check Challenge-0 existence
      run: |
        CHALLENGE_PATH="challenges/0-hello-world"
        if [ -d "$CHALLENGE_PATH" ]; then
          echo "Challenge-0 exists. Proceeding..."
          # Add your logic here to check completion or perform further steps
        else
          echo "Challenge-0 does not exist. Skipping the workflow."
          exit 78  # Exiting with a neutral exit code to indicate skipping
        fi