name: Check Challenge-0 Completion

on:
  workflow_dispatch:
  push:
    paths:
      - 'challenges/**'

jobs:
  check-challenge-0:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug Info
      run: |
        ls -R challenges

    - name: Check Challenge-0 completion
      run: |
        CHALLENGE_PATH="challenges/challenge-0"
        if [ -d "$CHALLENGE_PATH" ]; then
          echo "Challenge-0 exists. Checking completion status..."
          # Add your logic here to check completion
        else
          echo "Challenge-0 does not exist."
        fi
