name: Check Challenge-0 Completion

on:
  pull_request:
    paths:
      - 'challenges/**'

jobs:
  check-challenge-0:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug Info
      run: |
        ls -R challenges

    - name: Check Challenge-0 completion
      run: |
        CHALLENGE_PATH="challenges/0-hello-world"

        # Loop em cada pasta de lang
        for LANG_FOLDER in "$CHALLENGE_PATH"/*; do
          if [ -d "$LANG_FOLDER" ]; then
            GITHUB_USERNAME="$GITHUB_ACTOR"
            USER_PATH="$LANG_FOLDER/$GITHUB_USERNAME"

            if [ -d "$USER_PATH" ]; then
              echo "Challenge-0 completado por $GITHUB_USERNAME na linguagem: $(basename "$LANG_FOLDER")."
              
              exit 0  # Sucesso
            fi
          fi
        done

        # Se não entregar falha a action
        echo "Challenge-0 não foi entregue por $GITHUB_USERNAME em nenhuma linguagem."
        exit 1
